export const GET_USER_IDENTITY_API = 'GET_USER_IDENTITY_API';
export const GET_USER_IDENTITY_FAILED = 'GET_USER_IDENTITY_FAILED';
export const GET_USER_IDENTITY_SUCCESSFULLY = 'GET_USER_IDENTITY_SUCCESSFULLY';
export const TOKEN_NOT_FOUND = 'TOKEN_NOT_FOUND';

// Login
export const ATTEMPT_LOGIN_API = 'ATTEMPT_LOGIN_API';
export const ATTEMPT_LOGIN_FAILED = 'ATTEMPT_LOGIN_FAILED';
export const ATTEMPT_LOGIN_SUCCESSFULLY = 'ATTEMPT_LOGIN_SUCCESSFULLY';

// Register
export const ATTEMPT_REGISTER_API = 'ATTEMPT_REGISTER';
export const ATTEMPT_REGISTER_FAILED = 'ATTEMPT_REGISTER_FAILED';
export const ATTEMPT_REGISTER_SUCCESSFULLY = 'ATTEMPT_REGISTER_SUCCESSFULLY';

// Logout
export const ATTEMPT_LOGOUT = 'ATTEMPT_LOGOUT';

// Requests
export const CREATE_REQUEST_API = 'CREATE_REQUEST_API';
export const CREATE_REQUEST_SUCCESSFULLY = 'CREATE_REQUEST_SUCCESSFULLY';
export const CREATE_USER_FAILED = 'CREATE_USER_FAILED';
export const CREATE_REQUEST_FAILED = 'CREATE_REQUEST_FAILED';
export const GET_REQUESTS_API = 'GET_REQUESTS_API';
export const GET_REQUESTS_SUCCESSFULLY = 'GET_REQUESTS_SUCCESSFULLY';
export const GET_REQUESTS_FAILED = 'GET_REQUESTS_FAILED';
export const UPDATE_REQUEST_API = 'UPDATE_REQUEST_API';
export const UPDATE_REQUEST_FILTERED_API = 'UPDATE_REQUEST_FILTERED_API';
export const UPDATE_REQUEST_FILTERED_SUCCESSFULLY = 'UPDATE_REQUEST_FILTERED_SUCCESSFULLY';
export const UPDATE_REQUEST_FILTERED_FAILED = 'UPDATE_REQUEST_FILTERED_FAILED';
export const UPDATE_REQUEST_SUCCESSFULLY = 'UPDATE_REQUEST_SUCCESSFULLY';
export const UPDATE_REQUEST_FAILED = 'UPDATE_REQUEST_FAILED';
export const DELETE_REQUEST_API = 'DELETE_REQUEST_API';
export const DELETE_REQUEST_SUCCESSFULLY = 'DELETE_REQUEST_SUCCESSFULLY';
export const DELETE_REQUEST_FAILED = 'DELETE_REQUEST_FAILED';
export const UPDATE_REQUEST_API_IN_DOCTOR = 'UPDATE_REQUEST_API_IN_DOCTOR'
// User
export const UPDATE_USER_API = 'UPDATE_USER_API';
export const UPDATE_USER_API_NEW = 'UPDATE_USER_API_NEW';
export const UPDATE_USER_SUCCESSFULLY = 'UPDATE_USER_SUCCESSFULLY';
export const UPDATE_USER_FAILED = 'UPDATE_USER_FAILED';
export const CREATE_USER_API = 'CREATE_USER_API';
export const CREATE_USER_SUCCESSFULLY = 'CREATED_USER_SUCCESSFULLY';
export const GET_DOCTOR_LIST_API = 'GET_DOCTOR_LIST_API';
export const GET_DOCTOR_LIST_SUCCESSFULLY = 'GET_DOCTOR_LIST_SUCCESSFULLY';
export const GET_DOCTOR_LIST_FAILED = 'GET_DOCTOR_LIST_FAILED';
export const GET_PATIENT_LIST_API = 'GET_PATIENT_LIST_API';
export const GET_PATIENT_LIST_SUCCESSFULLY = 'GET_PATIENT_LIST_SUCCESSFULLY';
export const GET_PATIENT_LIST_FAILED = 'GET_PATIENT_LIST_FAILED';
export const GET_USERS_ID_API = 'GET_USERS_ID_API';
export const GET_USERS_ID_SUCCESSFULLY = 'GET_USERS_ID_SUCCESSFULLY';
export const GET_USERS_ID_FAILED = 'GET_USERS_ID_FAILED';
export const DELETE_USER_API = 'DELETE_USER_API';
export const DELETE_USER_SUCCESSFULLY = 'DELETE_USER_SUCCESSFULLY';
export const DELETE_USER_FAILED = 'DELETE_USER_FAILED';

// Forgot Password
export const FORGOT_PASSWORD_API = 'FORGOT_PASSWORD_API';
export const FORGOT_PASSWORD_SUCCESSFULLY = 'FORGOT_PASSWORD_SUCCESSFULLY';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const RESET_PASSWORD_API = 'RESET_PASSWORD_API';
export const RESET_PASSWORD_SUCCESSFULLY = 'RESET_PASSWORD_SUCCESSFULLY';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

// Appointment
export const CREATE_APPOINTMENT_API = 'CREATE_APPOINTMENT_API';
export const CREATE_APPOINTMENT_SUCCESSFULLY =
  'CREATE_APPOINTMENT_SUCCESSFULLY';
export const CREATE_APPOINTMENT_FAILED = 'CREATE_APPOINTMENT_FAILED';

export const GET_APPOINTMENTS_API = 'GET_APPOINTMENTS_API';
export const GET_APPOINTMENTS_SUCCESSFULLY = 'GET_APPOINTMENTS_SUCCESSFULLY';
export const GET_APPOINTMENTS_FAILED = 'GET_APPOINTMENTS_FAILED';

// Robot
export const GET_ROBOT_API = 'GET_ROBOT_API';
export const GET_ROBOT_SUCCESSFULLY = 'GET_ROBOT_SUCCESSFULLY';
export const GET_ROBOT_FAILED = 'GET_ROBOT_FAILED';

export const GET_ADMIN_ROBOTS_API = 'GET_ADMIN_ROBOTS_API';
export const GET_ADMIN_ROBOTS_SUCCESSFULLY = 'GET_ADMIN_ROBOTS_SUCCESSFULLY';
export const GET_ADMIN_ROBOTS_FAILED = 'GET_ADMIN_ROBOTS_FAILED'

export const GET_ADMIN_ROBOT_API = 'GET_ADMIN_ROBOT_API';
export const GET_ADMIN_ROBOT_SUCCESSFULLY = 'GET_ADMIN_ROBOT_SUCCESSFULLY';
export const GET_ADMIN_ROBOT_FAILED = 'GET_ADMIN_ROBOT_FAILED'

export const UPDATE_ADMIN_ROBOT_API = 'UPDATE_ADMIN_ROBOT_API';
export const UPDATE_ADMIN_ROBOT_SUCCESSFULLY = 'UPDATE_ADMIN_ROBOT_SUCCESSFULLY';
export const UPDATE_ADMIN_ROBOT_FAILED = 'UPDATE_ADMIN_ROBOT_FAILED'

export const SYNC_ROBOTS_API = 'SYNC_ROBOTS_API';
export const SYNC_ROBOTS_SUCCESSFULLY = 'SYNC_ROBOTS_SUCCESSFULLY';
export const SYNC_ROBOTS_FAILED = 'GET_ADMIN_ROBOTS_FAILED'

export const BOOK_APPOINTMENT_API = 'BOOK_APPOINTMENT_API';
export const BOOK_APPOINTMENT_SUCCESSFULLY = 'BOOK_APPOINTMENT_SUCCESSFULLY';
export const BOOK_APPOINTMENT_FAILED = 'BOOK_APPOINTMENT_FAILED';

export const CANCEL_APPOINTMENT_API = 'CANCEL_APPOINTMENT_API';
export const CANCEL_APPOINTMENT_SUCCESSFULLY =
  'CANCEL_APPOINTMENT_SUCCESSFULLY';
export const CANCEL_APPOINTMENT_FAILED = 'CANCEL_APPOINTMENT_FAILED';

export const UPDATE_APPOINTMENT_API = 'UPDATE_APPOINTMENT_API';
export const UPDATE_APPOINTMENT_SUCCESSFULLY =
  'UPDATE_APPOINTMENT_SUCCESSFULLY';
export const UPDATE_APPOINTMENT_FAILED = 'UPDATE_APPOINTMENT_FAILED';

export const GET_ALL_APPOINTMENTS_API = 'GET_ALL_APPOINTMENTS_API';
export const GET_ALL_APPOINTMENTS_SUCCESSFULLY =
  'GET_ALL_APPOINTMENTS_SUCCESSFULLY';
export const GET_ALL_APPOINTMENTS_FAILED = 'GET_ALL_APPOINTMENTS_FAILED';

export const GET_ALL_APPOINTMENTS_CAO_THANG_API = 'GET_ALL_APPOINTMENTS_CAO_THANG_API';
export const GET_ALL_APPOINTMENTS_CAO_THANG_SUCCESSFULLY =
  'GET_ALL_APPOINTMENTS_CAO_THANG_SUCCESSFULLY';
export const GET_ALL_APPOINTMENTS_CAO_THANG_FAILED = 'GET_ALL_APPOINTMENTS_CAO_THANG_FAILED';

export const GET_ALL_APPOINTMENTS_DATE_IN_FUTURE_API =
  'GET_ALL_APPOINTMENTS_DATE_IN_FUTURE_API';
export const GET_ALL_APPOINTMENTS_DATE_IN_FUTURE_SUCCESSFULLY =
  'GET_ALL_APPOINTMENTS_DATE_IN_FUTURE_SUCCESSFULLY';
export const GET_ALL_APPOINTMENTS_DATE_IN_FUTURE_FAILED =
  'GET_ALL_APPOINTMENTS_DATE_IN_FUTURE_FAILED';

export const RECORD_APPOINTMENT = 'RECORD_APPOINTMENT';

// Token

export const TOKEN_KEY = 'userToken';
export const NULL_TOKEN = 'NULL_TOKEN';

// Notification
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const GET_NOTIFICATIONS_SUCCESSFULLY = 'GET_NOTIFICATIONS_SUCCESSFULLY';
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED';
export const MARK_AS_READ = 'MARK_AS_READ';

export const ENV = process.env.REACT_APP_STAGE;
export const API_URL = process.env.API_URL;

export const getHOST = () => {
  return process.env.REACT_APP_STAGE === 'prod'
    ? 'https://api.imi.ai/v2'
    : process.env.REACT_APP_STAGE === 'dev'
    ? 'https://dev-api.imi.ai/v2'
    : 'http://localhost:5000/v2';
};

export const HOST_FE = 'https://dev-dashboard.imi.ai/';
export const HOST = getHOST();

// Firebase
export const FIREBASE_REGISTRATION_TOKEN = 'FIREBASE_REGISTRATION_TOKEN';
export const PUBLIC_VAPID_KEY =
  'BAHUc_bWeRJUMzEtOSxe_nlTCkzirbGfcq_Iru9_6JqdmPfUZJMFQ--1CDzBBAEJ7XeXwuBL5f63T4tI_HSNa8E';

// Auth
export const IDENTITY_URI = '/identity';
export const LOGIN_URI = '/login';
export const USERS_URI = '/users';
export const FIREBASE_URI = '/firebase';
export const FILE_UPLOAD_URI =
  'https://us-central1-imi-server.cloudfunctions.net/TestResultFileUploadFunction';
export const FILE_AUDIO_APPOINTMENT_UPLOAD_URI =
  'https://us-central1-imi-server.cloudfunctions.net/pus-burnside';
export const OLD_FILE_UPLOAD_URI = '/file-upload';
export const FILE_URI = '/file';
export const REQUESTS_URI = '/requests';
export const APPOINTMENT_URI = '/appointment';
export const NOTIFICATION_URI = '/notification';

// Forgot + Reset Password URI
export const FORGOT_PASSWORD_URI = '/forgot-password';

// Error
export const EMAIL_IS_IN_WRONG_FORMAT = 'Email is in wrong format';
export const PASSWORD_DOES_NOT_SATISFY_REQUIREMENT =
  'Password must be 8-16 characters, contain at least 1 uppercase letter, 1 special character !,@,#,$,%,etc., and 1 number [0-9]';
export const PASSWORD_DOES_NOT_MATCH = 'Confirmed password does not match';
export const PASSWORD_LENGTH_MUST_BE_MORE_THAN_8 =
  'Password length must be more than 8';
export const PASSWORD_CONTAIN_A_SPECIAL_CHARACTER =
  'Password should contain 1 special character !,@,#,$,%';
export const PASSWORD_CONTAIN_A_LOWERCASE_CHARACTER =
  'Password should contain 1 lowercase character';
export const PASSWORD_CONTAIN_A_UPPERCASE_CHARACTER =
  'Password should contain 1 uppercase character';
export const PASSWORD_CONTAIN_A_NUMBER = 'Password should contain a number';
export const ROLE_DOES_NOT_SELECTED = 'Role is not selected';
export const ERRORS = {
  email: {
    USER_DOES_NOT_EXIST: 'User does not exist',
    USER_EXISTS_ALREADY: 'User already existed',
    EMAIL_IS_NOT_CONFIRMED: 'Email is not confirmed',
    EMAIL_IS_EMPTY: 'Email is empty',
    EMAIL_IS_IN_WRONG_FORMAT: 'email is in wrong format',
  },
  password: {
    WRONG_PASSWORD: 'Wrong password',
    TOKEN_IS_EXPIRED: 'Token is expired or has been used',
    TOKEN_IS_INVALID: 'Token is invalid',
    PASSWORD_IS_THE_SAME_AS_CURRENT_PASSWORD: 'You enter an old password.',
    FAILED_TO_UPDATE_USER: 'Failed to Update User',
    PASSWORD_IS_EMPTY: 'Wrong password',
    PASSWORD_LENGTH_MUST_BE_MORE_THAN_8: 'Wrong password',
  },
  server: {
    SOME_THING_WENT_WRONG: 'Something went wrong',
  },
};

export const UNKNOWN_ERROR = 'Unknown Error';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const IMAGE_TYPES = ['image/jpeg', 'image/gif', 'image/png'];
export const PDF_TYPE = 'application/pdf';
export const IMAGE_MODE = 'img';
export const PDF_MODE = 'pdf';

export const PATIENT_ROLE = 'patient';
export const DOCTOR_ROLE = 'doctor';
export const ADMIN_ROLE = 'admin';
export const PAGE_LIMIT = 20;

export const VERSION_ID = 'VERSION_ID';

export const GET_MEDICAL_HISTORY = 'GET_MEDICAL_HISTORY'
export const GET_MEDICAL_HISTORY_SUCCESSFULLY = 'GET_MEDICAL_HISTORY_SUCCESSFULLY'
export const GET_MEDICAL_HISTORY_FAILED = "GET_MEDICAL_HISTORY_FAILED"
export const UPDATE_MEDICAL_HISTORY = 'UPDATE_MEDICAL_HISTORY'
export const UPDATE_MEDICAL_HISTORY_SUCCESSFULLY = 'UPDATE_MEDICAL_HISTORY_SUCCESSFULLY'
export const UPDATE_MEDICAL_HISTORY_FAILED = 'UPDATE_MEDICAL_HISTORY_FAILED'

export const SEND_FORGOT_PASSWORD_API = 'SEND_FORGOT_PASSWORD_API'
export const SEND_FORGOT_PASSWORD_SUCCESSFULLY = 'SEND_FORGOT_PASSWORD_SUCCESSFULLY'
export const SEND_FORGOT_PASSWORD_FAILED = 'SEND_FORGOT_PASSWORD_FAILED'

export const SET_HOME_PAGE = 'SET_HOME_PAGE'
export const SET_HOME_PAGE_SUCCESSFULLY = 'SET_HOME_PAGE_SUCCESSFULLY'
export const SET_HOME_PAGE_FAILED = 'SET_HOME_PAGE_FAILED'

export const GET_REMOTE_LINK = 'GET_REMOTE_LINK'
export const GET_REMOTE_LINK_SUCCESSFULLY = 'GET_REMOTE_LINK_SUCCESSFULLY'
export const GET_REMOTE_LINK_FAILED = 'GET_REMOTE_LINK_FAILED'

export const DELETE_REMOTE_LINK = 'DELETE_REMOTE_LINK'
export const DELETE_REMOTE_LINK_SUCCESSFULLY = 'DELETE_REMOTE_LINK_SUCCESSFULLY'
export const DELETE_REMOTE_LINK_FAILED = 'DELETE_REMOTE_LINK_FAILED'

export const GET_TEST_RESULT = 'GET_TEST_RESULT'
export const GET_TEST_RESULT_SUCCESSFULLY = 'GET_TEST_RESULT_SUCCESSFULLY'
export const GET_TEST_RESULT_FAILED = 'GET_TEST_RESULT_FAILED'

export const GET_TEXT_RECORDING = 'GET_TEXT_RECORDING'
export const GET_TEXT_RECORDING_SUCCESSFULLY = 'GET_TEXT_RECORDING_SUCCESSFULLY'
export const GET_TEXT_RECORDING_FAILED = 'GET_TEXT_RECORDING_FAILED'

export const GET_SMART_READER_DOCTOR_API = 'GET_SMART_READER_DOCTOR_API'
export const GET_SMART_READER_DOCTOR_SUCCESSFULLY = 'GET_SMART_READER_DOCTOR_SUCCESSFULLY'
export const GET_SMART_READER_DOCTOR_FAILED = 'GET_SMART_READER_DOCTOR_FAILED'